name: Semgrep SCA
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  pull_request: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/semgrep-sca.yaml
jobs:
  semgrep-sca:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci --sca || [ $? == 1 ]
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
